{"name": "账号密码错误登录", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './TestData/main.yml'", "trace": "self = <zikaow.TestCase.test_login.TestLogin object at 0x000002E050D135B0>\n\n    def setup(self):  # 方法运行前执行一次\n>       self.loginPage = self.testDriver.go_my_login()\n\ntest_login.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\Page\\main.py:13: in go_my_login\n    self.steps('./TestData/main.yml', 'go_my_login')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <zikaow.Page.main.Main object at 0x000002E04FFD4460>\npath = './TestData/main.yml', key = 'go_my_login', kwargs = {}\n\n    def steps(self, path, key, **kwargs):  # 定义操作步骤的方法，用于通过编写配置文件，执行相关用例\n>       with open(path, 'r', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './TestData/main.yml'\n\n..\\Page\\basepage.py:114: FileNotFoundError"}, "parameters": [{"name": "user", "value": "'1910012'"}, {"name": "pw", "value": "'123456'"}, {"name": "msg", "value": "'账号错误'"}], "start": 1622737798393, "stop": 1622737798393, "uuid": "e2824c9f-5efc-47f4-a382-f9efb4cc3d4d", "historyId": "c1b75ee7fb611cfa95613a2a2509343b", "testCaseId": "351efa5f97d628365da09acf6a5e9ba8", "fullName": "TestCase.test_login.TestLogin#test_log_error", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-TCP89B8"}, {"name": "thread", "value": "10156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}